### ISSUE TITLE
Build Linux wheels

### ISSUE THREAD

**Issue by EwoutH** [michelbierlaire/cythonbiogeme#1]
Currently cythonbiogeme only has macOS and Windows wheels [uploaded at PyPI](https://pypi.org/project/cythonbiogeme/#files). It would be useful if there would also be Linux wheels available.

[cibuildwheel](https://github.com/pypa/cibuildwheel) can potentially help with building the wheels in a more automated and robust way, and so reduce maintenance effort. There are [some examples](https://cibuildwheel.readthedocs.io/en/stable/working-examples/) of cibuildwheel being used with cython builds.

**Comment by EwoutH** [comment]
@michelbierlaire if you can show me the current way (ideally in code or scripts) of building the wheels, I would be willing to help setup cibuildwheel.

**Comment by michelbierlaire** [comment]
Thank you!
In the past, I used `python setup.py bdist_wheel` on MacOs. But now I use `pip wheel . -w dist`
On Windows, it is more complicated. But Linux. should be as simple as MacOs.
