### ISSUE TITLE
setup.py overrides externally applied environment variables

### ISSUE THREAD

**Issue by moorepants** [michelbierlaire/cythonbiogeme#6]
The setup.py file includes:

```
if platform.system() == "Darwin":
    os.environ["CC"] = "clang++"
    os.environ["CXX"] = "clang++"
else:
    os.environ["CC"] = "g++"
    os.environ["CXX"] = "g++"
```

This prevents someone building the package from setting their desired values for `CC` and `CXX`. The paths to the compiler executables may have different names or paths on the build system.

**Comment by michelbierlaire** [comment]
It was done a while ago because the code would not compile with another compiler. 
How would you suggest to do differently?

**Comment by moorepants** [comment]
You could  check if those environment variables are empty and then set them to your defaults. Something like:

```
os.getenv('CXX', 'clang++' if platform.system() == 'Darwin' else 'g++')
```

That should let the externally set values override your defaults.

**Comment by michelbierlaire** [comment]
Thank you. I have changed it and will test it for the next release.
