### ISSUE TITLE
setup.cfg specifies link args that are not available on all operating systems

### ISSUE THREAD

**Issue by moorepants** [michelbierlaire/cythonbiogeme#7]
On Windows setting a link arg to `-std=c++11` will throw a compilation error. This arg is only needed for gcc. You have these lines in the `setup.cfg`:

```
extra_compile_args = -std=c++11
extra_link_args = -std=c++11
```

which causes build failures on windows.

**Comment by michelbierlaire** [comment]
No, the arg is also valid for clang. Compiling in Windows also requires g++ ,but requires some manual "hacking". See https://biogeme.epfl.ch/#install

**Comment by moorepants** [comment]
I'm trying to build with MSVC on Windows. Am I guaranteed to fail with that?

**Comment by michelbierlaire** [comment]
I never succeeded, but i have stop trying as well. If you manage, let me know.

**Comment by moorepants** [comment]
We are attempting to build this for conda forge and the standard there is to build with MSVC. I also can't build with the static libs as you suggest in your documentation because that is not allowed in conda forge builds. I'll see where we get. We are iterating here, if interested: https://github.com/conda-forge/staged-recipes/pull/26374

**Comment by michelbierlaire** [comment]
The recent version 1.0.3 now compiles with MSVC.
